name: publish
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'kaskadi.js'
      - 'functions/**'
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Execute tests
      run: npm test
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
