name: testing + coverage
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'kaskadi'
      - 'functions/**'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
        coverageLocations: ./coverage/lcov.info:lcov
