name: testing + coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: npm i
    - name: coverage
    - uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
