name: testing + coverage

on: [push]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
      with:
        coverageCommand: npm coverage
        coverageLocations: ./coverage/lcov.info:lcov
